org: abcde123
app: sls-experiment
service: request-schedule

frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  lambdaHashingVersion: 20201221

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every hour
      - schedule: rate(1 hour)
